# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -o keydash -v ./...

    - name: Build for windowzzz
      run: GOOS=windows GOARCH=amd64 go build -o keydash.exe -v ./...

    - name: Test
      run: find . -name go.mod -execdir go test -v ./... \;

    - name: Create ZIP file with Bash script and Go binary
      run: |
        zip -r keydash.zip install.sh ./keydash
    
    - name: Build for MacOS (Apple Silicon)
      run: GOOS=darwin GOARCH=arm64 go build -o keydash -v ./...

    - name: Create ZIP file with Bash script and Go binary for ARM64
      run: |
        zip -r keydash-arm64.zip install.sh keydash

    - name: Get commit SHA
      id: commit_sha
      run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Upload Go binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: "go-binary-${{ env.COMMIT_SHA }}"
        path: "keydash.zip"

    - name: Upload Go binary for Windows as artifact
      uses: actions/upload-artifact@v4
      with:
        name: "go-binary-windows-${{ env.COMMIT_SHA }}"
        path: "./keydash.exe"

    - name: Upload Go binary for MacOS as artifact
      uses: actions/upload-artifact@v4
      with:
        name: "go-binary-arm64-${{ env.COMMIT_SHA }}"
        path: "keydash-arm64.zip"
